const ActionTypes = {};

export const PRIVACY_POLICY_WATCHER = 'PRIVACY_POLICY_WATCHER';
export const PRIVACY_POLICY_SUCCESS = 'PRIVACY_POLICY_SUCCESS';
export const PRIVACY_POLICY_FAILURE = 'PRIVACY_POLICY_FAILURE';

export const TERMS_CONDITIONS_WATCHER = 'TERMS_CONDITIONS_WATCHER';
export const TERMS_CONDITIONS_SUCCESS = 'TERMS_CONDITIONS_SUCCESS';
export const TERMS_CONDITIONS_FAILURE = 'TERMS_CONDITIONS_FAILURE';

//OFFLINE DATA CONSTANTS
export const REMOVE_OFFLINE_DATA="REMOVE_OFFLINE_DATA";
export const GET_OFFLINE_DATA="GET_OFFLINE_DATA";
export const ADD_OFFLINE_DATA = 'ADD_OFFLINE_DATA';
export const UPDATE_OFFLINE_DATA = 'UPDATE_OFFLINE_DATA';
export const UPDATE_OFFLINE_DATA_STATUS = 'UPDATE_OFFLINE_DATA_STATUS';
export const INDEX_OFFLINE_DATA="INDEX_OFFLINE_DATA";
export const DELETE_OFFLINE_DATA = 'DELETE_OFFLINE_DATA';
export const ERR_OFFLINE_DATA = 'ERR_OFFLINE_DATA';
export const LOADING_OFFLINE_DATA = 'LOADING_OFFLINE_DATA';

//SUBSCRIPTOIN CONSTANTS
export const SUBSCRIPTION_LOADING= "SUBSCRIPTION_LOADING";
export const ADD_SUBSCRIPTION_INFO = "ADD_SUBSCRIPTION_INFO";
export const REMOVE_SUBSCRIPTION_INFO= "REMOVE_SUBSCRIPTION_INFO";
export const UPDATE_SUBSCRIPTOIN_INFO = "UPDATE_SUBSCRIPTOIN_INFO";
export const CANCEL_SUBSCRIPTION_INFO = "CANCEL_SUBSCRIPTION_INFO";
export const UPDATE_OFFLINE_API_CALLS = "UPDATE_OFFLINE_API_CALLS";
export const ADD_OFFLINE_API_CALLS ="ADD_OFFLINE_API_CALLS";
export const REMOVE_OFFLINE_APIS = "REMOVE_OFFLINE_APIS";

//NOTIFICATION CONTANTS
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

//USERPROFILE CONTANTS
export const ADD_USER_DATA = "ADD_USER_DATA";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";

//TERMS & CONDITION CONTANTS
export const ADD_TERMS = "ADD_TERMS";
export const ADD_POLICY = "ADD_POLICY";


export default ActionTypes;

