const AsynchStoragekey = {
  LOGIN_TOKEN: 'LOGIN_TOKEN',
  LOGIN_ID: 'LOGIN_ID',
  USER_INFO: 'USER_INFO',
  USER_CREDITCARDID: 'USER_CREDITCARDID',
  USER_SUBSCRIPTION: 'USER_SUBSCRIPTION',
  REGISTER_ACC_TYPE: 'REGISTER_ACC_TYPE',
  APPLE_CRED_DATA: 'APPLE_CRED_DATA',
  FCM_TOKEN: 'FCM_TOKEN',
  NOTIFICATION_UNREAD: 'NOTIFICATION_UNREAD',
  COURCE_NAME: 'COURCE_NAME',
  DASHBOARD_OFFLINE_DATA: 'DASHBOARD_OFFLINE_DATA',
  ALL_LESSON: 'ALL_LESSON',
  FLASH_CARDS: 'FLASH_CARDS',
  MOCK_EXAMS: 'MOCK_EXAMS',
  QUIZ_EXAM: 'QUIZ_EXAM',
  COURSE_DETAIL: 'COURSE_DETAIL',
  QUIZ_EXAM_DROPDOWN_LIST: 'QUIZ_EXAM_DROPDOWN_LIST',
  MOCK_EXAM_DROPDOWN_LIST: 'MOCK_EXAM_DROPDOWN_LIST',
  OFFLINE_DATA: 'OFFLINE_DATA',
  SUBSCRIPTION_STATUS:'SUBSCRIPTION_STATUS',
  SUBSCRIPTION_TRANSACTION_DATE: 'SUBSCRIPTION_TRANSACTION_DATE',
  SUBSCRIPTION_EXPIRY_DATE: 'SUBSCRIPTION_EXPIRY_DATE',
  SUBSCRIPTION_TRANSACTION_RECEIPT: 'SUBSCRIPTION_TRANSACTION_RECEIPT',
  SUBSCRIPTION_RENEWAL_DATE: "SUBSCRIPTION_RENEWAL_DATE"
};

export default {AsynchStoragekey};
