import type { ComponentType } from "react";

/**
 * Stack route name → legacy block (same modules as packages/mobile/App.tsx).
 * Each require path is a literal string so Metro can bundle dependencies.
 */
export const LEGACY_BLOCK_REGISTRY: Record<string, ComponentType<Record<string, unknown>>> = {
  Landing: require("../../../packages/blocks/LandingScreen/src/Landing").default,
  Home: require("../../../packages/components/src/HomeScreen").default,
  InfoPage: require("../../../packages/blocks/info-page/src/InfoPageBlock").default,
  EmailNotifications: require("../../../packages/blocks/EmailNotifications/src/EmailNotifications").default,
  CfAppleLogin17: require("../../../packages/blocks/CfAppleLogin17/src/CfAppleLogin17").default,
  BulkUploading: require("../../../packages/blocks/BulkUploading/src/BulkUploading").default,
  SocialMediaAccountLoginScreen: require("../../../packages/blocks/social-media-account-login/src/SocialMediaAccountLoginScreen")
    .default,
  CfFlashcards2: require("../../../packages/blocks/CfFlashcards2/src/CfFlashcards2").default,
  AssessmentTest: require("../../../packages/blocks/AssessmentTest/src/AssessmentTest").default,
  LanguageOptions: require("../../../packages/blocks/LanguageOptions/src/LanguageOptions").default,
  LanguageOptionModal: require("../../../packages/blocks/LanguageOptions/src/LanguageOptionsModal").default,
  Polling: require("../../../packages/blocks/Polling/src/Polling").default,
  Customisableusersubscriptions: require("../../../packages/blocks/customisableusersubscriptions/src/Customisableusersubscriptions")
    .default,
  SubscriptionDetails: require("../../../packages/blocks/customisableusersubscriptions/src/SubscriptionDetails").default,
  SubscriptionBilling: require("../../../packages/blocks/SubscriptionBilling/src/SubscriptionBilling").default,
  Search: require("../../../packages/blocks/search/src/Search").default,
  Leaderboard: require("../../../packages/blocks/Leaderboard/src/Leaderboard").default,
  ForgotPassword: require("../../../packages/blocks/forgot-password/src/ForgotPassword").default,
  ForgotPasswordOTP: require("../../../packages/blocks/forgot-password/src/ForgotPasswordOTP").default,
  NewPassword: require("../../../packages/blocks/forgot-password/src/NewPassword").default,
  Sorting: require("../../../packages/blocks/sorting/src/Sorting").default,
  Library2: require("../../../packages/blocks/Library2/src/Library2").default,
  Contactus: require("../../../packages/blocks/contactus/src/Contactus").default,
  AddContactus: require("../../../packages/blocks/contactus/src/AddContactus").default,
  CountryCodeSelector: require("../../../packages/blocks/country-code-selector/src/CountryCodeSelector").default,
  CountryCodeSelectorTable: require("../../../packages/blocks/country-code-selector/src/CountryCodeSelectorTable")
    .default,
  StripeIntegration: require("../../../packages/blocks/StripeIntegration/src/StripeIntegration").default,
  Gamification: require("../../../packages/blocks/Gamification/src/Gamification").default,
  AdminConsole3: require("../../../packages/blocks/AdminConsole3/src/AdminConsole3").default,
  OTPInputAuth: require("../../../packages/blocks/otp-input-confirmation/src/OTPInputAuth").default,
  Notes: require("../../../packages/blocks/Notes/src/Notes").default,
  EditProfile: require("../../../packages/blocks/user-profile-basic/src/EditProfile").default,
  ChangePassword: require("../../../packages/blocks/user-profile-basic/src/ChangePassword").default,
  ChangeEmail: require("../../../packages/blocks/user-profile-basic/src/ChangeEmail").default,
  EmailAccountLoginBlock: require("../../../packages/blocks/email-account-login/src/EmailAccountLoginBlock").default,
  TermsAndConditions: require("../../../packages/blocks/TermsAndConditions/src/TermsAndConditions").default,
  Pushnotifications: require("../../../packages/blocks/pushnotifications/src/Pushnotifications").default,
  DataImportexportcsv: require("../../../packages/blocks/DataImportexportcsv/src/DataImportexportcsv").default,
  Annotations: require("../../../packages/blocks/Annotations/src/Annotations").default,
  Scoring: require("../../../packages/blocks/Scoring/src/Scoring").default,
  PaymentAdmin2: require("../../../packages/blocks/PaymentAdmin2/src/PaymentAdmin2").default,
  EmailAccountRegistration: require("../../../packages/blocks/email-account-registration/src/EmailAccountRegistration")
    .default,
  ContentManagement: require("../../../packages/blocks/ContentManagement/src/ContentManagement").default,
  Splashscreen: require("../../../packages/blocks/splashscreen/src/Splashscreen").default,
  SPLASH: require("../../../packages/blocks/splashscreen/src/Splashscreen").default,
  QuestionBank: require("../../../packages/blocks/QuestionBank/src/QuestionBank").default,
  Categoriessubcategories: require("../../../packages/blocks/categoriessubcategories/src/Categoriessubcategories")
    .default,
  Settings5: require("../../../packages/blocks/Settings5/src/Settings5").default,
  UserProfileBasicBlock: require("../../../packages/blocks/user-profile-basic/src/UserProfileBasicBlock").default,
  Dashboard: require("../../../packages/blocks/dashboard/src/Dashboard").default,
  Filteritems: require("../../../packages/blocks/filteritems/src/Filteritems").default,
  Filteroptions: require("../../../packages/blocks/filteritems/src/Filteroptions").default,
  SocialMediaAccountRegistrationScreen: require("../../../packages/blocks/social-media-account-registration/src/SocialMediaAccountRegistrationScreen")
    .default,
  Notifications: require("../../../packages/blocks/notifications/src/Notifications").default,
  Catalogue: require("../../../packages/blocks/catalogue/src/Catalogue").default,
  ManageNotifications: require("../../../packages/blocks/user-profile-basic/src/ManageNotifications").default,
  SubCriptionScreen: require("../../../packages/blocks/SubCriptionScreen/src/Subcription").default,
  SubcriptionSuccsess: require("../../../packages/blocks/SubCriptionScreen/src/SubcriptionSuccsess").default,
  OverView: require("../../../packages/blocks/catalogue/src/OverView").default,
  OverViews: require("../../../packages/blocks/catalogue/src/OverView").default,
  FilterModal: require("../../../packages/blocks/catalogue/src/FilterModal").default,
  StartCourceModal: require("../../../packages/blocks/catalogue/src/StartCourceModal").default,
  TakeQuizeModal: require("../../../packages/blocks/catalogue/src/TakeQuizeModal").default,
  MockExamModal: require("../../../packages/blocks/catalogue/src/MockExamModal").default,
  ReviewModal: require("../../../packages/blocks/catalogue/src/ReviewModal").default,
  CatalogueFive: require("../../../packages/blocks/catalogue/src/CatalogueFIve").default,
  settings: require("../../../packages/blocks/user-profile-basic/src/settings").default,
  Themes: require("../../../packages/blocks/catalogue/src/ThemesScr").default,
  /** Same as `Themes` — `themesRootStack` initial route key in v2. */
  ThemesScreen: require("../../../packages/blocks/catalogue/src/ThemesScr").default,
  /** Same component as `CatalogueFive` — `themesRootStack` route key from `OverView`. */
  ProductCategory: require("../../../packages/blocks/catalogue/src/CatalogueFIve").default,
  /** Same as `CatalogueStudy` — `themesRootStack` route key. */
  CatalogueStudies: require("../../../packages/blocks/catalogue/src/CatalogueStudy").default,
  CatalogueStudy: require("../../../packages/blocks/catalogue/src/CatalogueStudy").default,
  PollingScr: require("../../../packages/blocks/CfFlashcards2/src/PollingScr").default,
  WebviewComponent: require("../../../packages/blocks/contactus/Component/WebviewComponent").default,
  PasswordChanged: require("../../../packages/blocks/forgot-password/src/passwordChanged").default,
  NoInternet: require("../../../packages/blocks/Internet/src/Internet").default,
  CfFlashCardOne: require("../../../packages/blocks/catalogue/src/CfFlashCardOne").default,
  RevealAnswer: require("../../../packages/blocks/catalogue/src/RevealAnswer").default,
  Congratulation: require("../../../packages/blocks/catalogue/src/Congratulation").default,
  moxExamQuestionOne: require("../../../packages/blocks/catalogue/src/moxExamQuestionOne").default,
  ReArrangeOrder: require("../../../packages/blocks/catalogue/src/ReArrangeOrder").default,
  MocExamInit: require("../../../packages/blocks/catalogue/src/MocExamInit").default,
  QuizzesExamInit: require("../../../packages/blocks/catalogue/src/QuizzesExamInit").default
};
